'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CyborgAutoProfiler.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CAP() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CAP___Blue() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP___Blue", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CAP___Green() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP___Green", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CAP___Mag() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP___Mag", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        '''</summary>
        Friend ReadOnly Property CAP___Red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("CAP___Red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CommandUnit() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CommandUnit", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DPIMode0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DPIMode0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DPIMode1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DPIMode1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DPIMode2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DPIMode2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DPIMode3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DPIMode3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DPIMode4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DPIMode4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Flight() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Flight", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Gamepad() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Gamepad", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Infection() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Infection", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeyboardV1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyboardV1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property KeyboardV5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("KeyboardV5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Keyboardv7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Keyboardv7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; This script will show you how to close an application when a certain profile is being used.
        '''
        '''
        '''&apos;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        '''
        '''
        '''&apos; This is called when a profile is activated
        '''
        '''Sub LoadProfile
        ''' 
        '''
        '''   &apos; In this script we want to close &apos;uTorrent&apos; when the profile is activated.
        '''   &apos; We are using &apos;uTorrent.exe&apos; as an example in this script. Simply replace &apos;uTorrent.exe&apos; with the proces [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Kill_Process_Script() As String
            Get
                Return ResourceManager.GetString("Kill_Process_Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MMO7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MMO7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MMO7LED() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MMO7LED", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property msscript() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("msscript", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property None() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("None", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_BIB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_BIB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_Rudder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_Rudder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_Throttle() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_Throttle", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_TPM() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_TPM", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_X52() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_X52", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PF_Yoke() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PF_Yoke", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RAT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RAT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Cyborg Auto-Profiler 3.2.3
        '''
        '''by Danny Hasley
        '''http://CyborgAutoProfiler.com
        '''CyborgAutoProfiler@gmail.com
        '''
        '''
        '''Feel free to e-mail me any bugs, questions, or to request features.
        '''
        '''
        '''Special Thanks to:
        '''
        '''Michael Colesky for MMO7 LED Color assistance.
        '''
        '''M.M.O.7 LED Flow Motivated by the Razer Mamba 2012
        '''
        '''
        '''Beta Testers:
        '''André LMC
        '''Mark Chong
        '''Mike Parent
        '''Mike Edwards
        '''Black3v3r
        '''Sebastian Eberhard
        '''Tom Nigro
        '''SAK KING OF SA
        '''
        '''
        '''
        '''----Description----
        '''
        '''Cyborg Auto-Profiler is a lightweight, yet reli [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Read_Me() As String
            Get
                Return ResourceManager.GetString("Read_Me", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; This script will show you how to open an application when a certain profile is no longer being used
        '''
        '''&apos;////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        '''
        '''
        '''&apos; This is called when a profile is no longer activated.
        '''
        '''Sub UnloadProfile
        '''     
        '''    &apos; Now that the profile is no longer activated we want &apos;uTorrent&apos; to open back up. We&apos;ve also made it so it will start minimized to be out of the way.
        '''     Call Ru [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Run_Process_Script() As String
            Get
                Return ResourceManager.GetString("Run_Process_Script", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property Saitek_Devices() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("Saitek_Devices", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Selected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Selected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Byte[].
        '''</summary>
        Friend ReadOnly Property SpyCursorIcon() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("SpyCursorIcon", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SpyPic() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpyPic", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property STRIKE7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("STRIKE7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Swatch() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Swatch", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TaskMenu() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskMenu", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TaskProfileNormal() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskProfileNormal", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property TaskProfileSelected() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("TaskProfileSelected", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &apos; This script will show you how to open and close an application when a certain profile is being used, and no longer used.
        '''&apos; This is a good example of how you can exit software that could hog your Internet connection when opening a game that uses online functionality.
        '''&apos; Then when the game is exited and the default profile is activated it will open the software it closed back up.
        '''
        '''&apos;//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////// [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property uTorrent___Close_Open() As String
            Get
                Return ResourceManager.GetString("uTorrent___Close_Open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property WhiteRAT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("WhiteRAT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
